- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToTrueLiteralAnalyzerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToTrueLiteral/CompareBooleanToTrueLiteralAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToTrueLiteral/CompareBooleanToTrueLiteralCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
Implementation of CompareBooleanToTrueLiteral, #30
> Comparebooleantotrueliteral

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/TypeToVarAnalyzerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/TypeToVar/TypeToVarAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/TypeToVar/TypeToVarCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
> implement TypeToVar analyzer

- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/TypeToVar/TypeToVarAnalyzer.cs
I no longer have a skyrocketing memory usage and code fixes work properly though I am unsure if this was the actual cause.
> Added additional NRE handling to TypeToVar analyzer. 

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/SimplifyExpressionBodiedMemberAnalyzerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SimplifyExpressionBodiedMember/SimplifyExpressionBodiedMemberAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SimplifyExpressionBodiedMember/SimplifyExpressionBodiedMemberCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs
Fixes #97 and #98 by ignoring those members and fixes #99 by.. ignoring those members.
> Simplifyexpressionbodiedmember

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/app.config
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/packages.config
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostic.nuspec
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Async/AsyncMethodWithoutAsyncSuffix/AsyncMethodWithoutAsyncSuffixCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Exceptions/ArgumentExceptionWithoutNameofOperator/ArgumentExceptionWithoutNameofOperatorCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Exceptions/RethrowExceptionWithoutLosingStacktrace/RethrowExceptionWithoutLosingStacktraceCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToTrueLiteral/CompareBooleanToTrueLiteralCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionalOperatorReturnsDefaultOptions/ConditionalOperatorReturnsDefaultOptionsCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/IfStatementWithoutBraces/IfStatementWithoutBracesCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/NamingConventions/NamingConventionsCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/NonEncapsulatedOrMutableField/NonEncapsulatedOrMutableFieldCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/NullableToShorthand/NullableToShorthandCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/OnPropertyChangedWithoutNameOfOperator/OnPropertyChangedWithoutNameOfOperatorCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SimplifyExpressionBodiedMember/SimplifyExpressionBodiedMemberCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/TryCastWithoutUsingAsNotNull/TryCastWithoutUsingAsNotNullCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/TypeToVar/TypeToVarCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Strings/ReplaceEmptyStringWithStringDotEmpty/ReplaceEmptyStringWithStringDotEmptyCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Tests/TestMethodWithoutPublicModifier/TestMethodWithoutPublicModifierCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Properties/AssemblyInfo.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/packages.config
2 for the price of one! Yay! Apparently I forgot to merge the last one before my vacation.
> Merging 1.7.0-rc2 and 1.8.0 (stable) into master

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToFalseLiteralAnalyzerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToTrueLiteralAnalyzerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToFalseLiteral/CompareBooleanToFalseLiteralAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToFalseLiteral/CompareBooleanToFalseLiteralCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToTrueLiteral/CompareBooleanToTrueLiteralAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToTrueLiteral/CompareBooleanToTrueLiteralCodeFix.cs
> Close #115

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Attributes/AttributeWithEmptyArgumentListAnalyzerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/AttributeWithEmptyArgumentList/AttributeWithEmptyArgumentListAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/AttributeWithEmptyArgumentList/attributeWithEmptyArgumentListCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
> Close #110.  Implement check and fix for attributes with empty argument lists.

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/NamingConventionsTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers/ExplicitAccessModifiersAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/NamingConventions/NamingConventionsCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/packages.config
> Fix renaming bug

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ConditionalOperatorReturnsInvertedDefaultOptionsTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionalOperatorReturnsInvertedDefaultOptions/ConditionalOperatorReturnsInvertedDefaultOptionsAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionalOperatorReturnsInvertedDefaultOptions/ConditionalOperatorReturnsInvertedDefaultOptionsCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> ConditionalOperatorReturnsInvertedDefaultOptions analyzer and fix.

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/UseAliasesInsteadOfConcreteTypeTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers/ExplicitAccessModifiersAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers/ExplicitAccessModifiersCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/UseAliasesInsteadOfConcreteType/UseAliasesInsteadOfConcreteTypeAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/UseAliasesInsteadOfConcreteType/UseAliasesInsteadOfConcreteTypeCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> UseAliasesInsteadOfConcreteType analyzer and code fix.  Reference issue #22

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/FlagsEnumValuesAreNotPowersOfTwoTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/UseAliasesInsteadOfConcreteTypeTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/FlagsEnumValuesAreNotPowersOfTwo/FlagsEnumValuesAreNotPowersOfTwoAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/FlagsEnumValuesAreNotPowersOfTwo/FlagsEnumValuesAreNotPowersOfTwoCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/UseAliasesInsteadOfConcreteType/UseAliasesInsteadOfConcreteTypeAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/UseAliasesInsteadOfConcreteType/UseAliasesInsteadOfConcreteTypeCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Close #143

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Attributes/EnumCanHaveFlagsAttributeTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ExplicitAccessModifiersTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/FlagsEnumValuesAreNotPowersOfTwoTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/EnumCanHaveFlagsAttribute/EnumCanHaveFlagsAttributeAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/EnumCanHaveFlagsAttribute/EnumCanHaveFlagsAttributeCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/ObsoleteAttributeWithoutReason/ObsoleteAttributeWithoutReasonAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers/ExplicitAccessModifiersCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/FlagsEnumValuesAreNotPowersOfTwo/FlagsEnumValuesAreNotPowersOfTwoAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SingleEmptyConstructor/SingleEmptyConstructorAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/UseAliasesInsteadOfConcreteType/UseAliasesInsteadOfConcreteTypeAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
Close #149 
Close #151 
Close #152
> Fix several crash-causing bugs

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ConditionIsAlwaysFalseTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ConditionIsAlwaysTrueTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionIsAlwaysFalse/ConditionIsAlwaysFalseAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionIsAlwaysFalse/ConditionIsAlwaysFalseCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionIsAlwaysTrue/ConditionIsAlwaysTrueAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionIsAlwaysTrue/ConditionIsAlwaysTrueCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Basic condition is always true/false implementation.

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ExplicitAccessModifiersTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers/ExplicitAccessModifiersAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs
> Close #169

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ExplicitAccessModifiersTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/EnumCanHaveFlagsAttribute/EnumCanHaveFlagsAttributeCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers/ExplicitAccessModifiersAnalyzer.cs
> Prevent all interface members from having access modifier added.

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/LoopStatementWithoutBracesTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Strings/StringPlaceholdersInWrongOrderTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Tests/RemoveTestSuffixTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/LoopStatementWithoutBraces/LoopStatementWithoutBracesAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/LoopStatementWithoutBraces/LoopStatementWithoutBracesCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Strings/StringPlaceholdersInWrongOrder/StringPlaceholdersInWrongOrderAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Tests/RemoveTestSuffix/RemoveTestSuffixCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Feature194

- README.md
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Structs/StructMutateSelfTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Structs/StructShouldNotMutateSelfAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
I ended up adding a new diagnostic category for "structs", given that there are a few more open issues regarding structs, but I'm not sure what your policy is regarding category assignment.
> Add diagnostic for #258, a struct mutating itself.

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Attributes/FlagsEnumValuesAreNotPowersOfTwoTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/FlagsEnumValuesAreNotPowersOfTwoTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/FlagsEnumValuesAreNotPowersOfTwo/FlagsEnumValuesAreNotPowersOfTwoAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/FlagsEnumValuesAreNotPowersOfTwo/FlagsEnumValuesAreNotPowersOfTwoCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Flagsunderline

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/LoopedRandomInstantiationTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/SwitchDoesNotHandleAllEnumOptionsTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SwitchDoesNotHandleAllEnumOptions/SwitchDoesNotHandleAllEnumOptionsAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SwitchDoesNotHandleAllEnumOptions/SwitchDoesNotHandleAllEnumOptionsCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/DiagnosticId.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Close #211

- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/SwitchDoesNotHandleAllEnumOptions/SwitchDoesNotHandleAllEnumOptionsAnalyzer.cs
> Close #494

- README.md
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Arithmetic/DivideIntegerByIntegerTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Arithmetic/DivideIntegerByInteger/DivideIntegerByIntegerAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/DiagnosticId.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Implemented #236

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/EqualsAndGetHashcodeNotImplementedTogetherTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/EqualsAndGetHashcodeNotImplementedTogether/EqualsAndGetHashcodeNotImplementedTogetherAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/EqualsAndGetHashcodeNotImplementedTogether/EqualsAndGetHashcodeNotImplementedTogetherCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/DiagnosticId.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Close #172

- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Close #544

- README.md
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Structs/StructWithoutElementaryMethodsOverriddenTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/OnPropertyChangedWithoutCallerMemberName/OnPropertyChangedWithoutCallerMemberNameAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Structs/StructWithoutElementaryMethodsOverridden/StructWithoutElementaryMethodsOverriddenAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Structs/StructWithoutElementaryMethodsOverridden/StructWithoutElementaryMethodsOverriddenCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/DiagnosticId.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Feature185

- README.md
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/RedudantPrivateSetterTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Arithmetic/DivideIntegerByInteger/DivideIntegerByIntegerAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/RedundantPrivateSetter/RedundantPrivateSetterAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/RedundantPrivateSetter/RedundantPrivateSetterCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/DiagnosticId.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
Everything works except 1 test but this is due to an issue in RoslynTester, not VSDiagnostics. As soon as a new RoslynTester is released and we update VSDiagnostics, this branch will pass
> Redundantprivatesetter

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Attributes/OnPropertyChangedWithoutCallerMemberNameTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/OnPropertyChangedWithoutCallerMemberName/OnPropertyChangedWithoutCallerMemberNameAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/OnPropertyChangedWithoutCallerMemberName/OnPropertyChangedWithoutCallerMemberNameCodeFix.cs
The commit says "partial" because I thought I had a problem, but I don't.
> Fix for 553.

- README.md
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ImplementEqualsAndGetHashCodeTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/VSDiagnostics.Test.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ImplementEqualsAndGetHashCode/ImplementEqualsAndGetHashCodeAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ImplementEqualsAndGetHashCode/ImplementEqualsAndGetHashCodeCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/DiagnosticId.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnostics.csproj
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Implement #477

- README.md
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Attributes/AttributeWithEmptyArgumentListTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Tests/TestMethodWithoutTestAttributeTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Async/SyncMethodWithAsyncSuffix/SyncMethodWithAsyncSuffixAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Async/SyncMethodWithAsyncSuffix/SyncMethodWithAsyncSuffixCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Attributes/AttributeWithEmptyArgumentList/AttributeWithEmptyArgumentListAnalyzer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.Designer.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/VSDiagnosticsResources.resx
> Cleanupndaccess

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/TypeToVarTests.cs
> More TypeToVar tests

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToFalseLiteralTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/CompareBooleanToTrueLiteralTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ConditionalOperatorReturnsDefaultOptionsTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ConditionalOperatorReturnsInvertedDefaultOptionsTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToFalseLiteral/CompareBooleanToFalseLiteralCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/CompareBooleanToTrueLiteral/CompareBooleanToTrueLiteralCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionalOperatorReturnsDefaultOptions/ConditionalOperatorReturnsDefaultOptionsCodeFix.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ConditionalOperatorReturnsInvertedDefaultOptions/ConditionalOperatorReturnsInvertedDefaultOptionsCodeFix.cs
> Make some code fixes not reformat the entire document

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/General/ElementaryMethodsOfTypeInCollectionNotOverriddenTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ElementaryMethodsOfTypeInCollectionNotOverridden/ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer.cs
> Close #615

- VSDiagnostics/VSDiagnostics/VSDiagnostics.Test/Tests/Exceptions/ArgumentExceptionWithoutNameofOperatorTests.cs
- VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/Exceptions/ArgumentExceptionWithoutNameofOperator/ArgumentExceptionWithoutNameofOperatorAnalyzer.cs
> Close #618
